- client/src/components/application/Examine/CompName.vue
- client/src/components/application/Examine/NameMatches.vue
- client/src/components/application/NameExamination.vue
- client/src/components/application/sections/StdHeader.vue
- client/src/store/index.js
- fixed setting of User ID from login data.
- run recipes with every new NR that gets pulled from individual load; NOT when the NR is complete
- run recipes with every new NR from next off queue ("oldest")
- add "Examine" button to transition from HOLD to INPROGRESS
- remove manual search from complete NRs
- do green/red severity for conflicts and trademarks (green=no results, else red)
- do green/orange for history (green=no results, else orange)
> Various recipe steps/severity changes and button show/hide on state.

- client/src/components/application/Examine/RequestInfoHeader.vue
- client/src/components/application/Examine/nwpta/nwpta.vue
- client/src/store/index.js
- client/static/js/utils.js
*Issue #:* #653 
This handles displaying the various types of NWPTA/NUANS, display and editing. 
Assumptions:
- examiner cannot change which type of record this is, ie: from number (CO or LP), assumed name (AS), and assumed number (NAS).
- examiner cannot create a new nwpta record where one does not exist, ie: can't add a Saskatchewan record if it wasn't either requested (as a do-it-for-me request) or filled in by customer.
- we do not want to remove the data in the case of switching from a request type that uses/displays nwpta and one that does not. Ie: we don't clear the data if we switch away from a request type that does not need it. We just ignore it.
- all Additional Info canned text will be filled in by NRO when submitted by customer, and Namex will not …
> Added NWPTA view and edit functionality.

- client/src/components/application/Examine/CompName.vue
*Issue #:* n/a
Bug fix - reset comments breaking in API call - changed to be consistent with other comments in front end.
> Bug fix - reset comments breaking in API call - changed to be consistent

- client/src/components/application/Examine/RequestInfoHeader.vue
- client/src/store/index.js
*Issue #:* NO TICKET, JUST FOUND BUG.
Bug fix - current choice always 1 when coming back to HOLD NRs, even if it should be 2 or 3. Reset current choice upon new NR data so always correct. 
> Bug fix - current choice always 1 when coming back to HOLD NRs, even if

- client/src/components/application/Examine/CompName.vue
*Issue #:* #777 
Set manual search string every time coming back to Examine screen, even when returning to same NR.
Related to 777, possible due to previous fix, but not a fix for the original 777 bug.
> Set manual search string every time coming back to Examine screen

- client/index.html
*Issue #:* n/a
Updated path to keycloak.js - old path (dev-sso) stopped being available, so we switched to new domain (sso-dev).
> Updated keycloak.js path for new domain.

- client/src/components/application/Examine/RequestInfoHeader.vue
*Issue #:* #970 
Removed sync of closed NR from NRO to Namex. In discussions, we decided it was unnecessary and the master record after closing is Namex and no info (that is held in Namex) is updated by NRO.
> Removed sync of closed NR from NRO to Namex.

- client/src/components/application/Examine/RequestInfoHeader.vue
- client/src/components/auth/Signin.vue
- client/src/router/index.js
- client/src/store/index.js
*Issue #999 :*
changed confidential keycloak info to save in sessionStorage instead of localStorage
> token + token-refresh + auth flag moved to sessionStorage

- client/src/components/application/Examine/Recipe/conflicts/ConflictInfo.vue
- client/src/components/application/Examine/Recipe/conflicts/conflictInfoType/corpMatch.vue
- client/src/components/application/Examine/Recipe/conflicts/conflictInfoType/namesMatch.vue
- client/static/css/main.css
*Issue #: #1000 *
@katiemcgoff and I just noticed this morning that the corpname component didn't reflect the larger fonts requested.
Updated that, and also removed the p font in main.css that I had added the last Friday and meant to take out but ran it over with one of my merges/rebases
> Update font for corporate section

- client/src/components/application/Find/findFilter.vue
*Issue #1047:*
nr/examiner/compname do not fire off request until > 3 chars are in their string (unless they are cleared)
> search page update to NR/Examiner/Comp name fields

- client/src/components/application/Examine/InternalComments.vue
- client/src/components/application/Examine/RequestInfoHeader.vue
*Issue #:* #1055 
Handle empty comments better (null rather than '') so blank comment doesn't flash on screen.
> Handle empty comments better (null rather than '') so blank comment doesn't flash on screen.

- client/src/components/application/Examine/CompName.vue
- client/src/store/index.js
*Issue #: #993 *
- Clear the  condition when the examiner accepts the name.  This way it is gone when they go to getNext, or go back and examine the next name, but it remains when they go back without accepting.
> Issue #993 stuck conditions

- client/src/store/index.js
- client/test/unit/specs/ExactMatchesRequest.spec.js
*Issue #:*
we now send encoded query to /exact-match
we also remove the leading plus if any
> 1159 - we now send encoded query to /exact-match

- client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue
*Issue #:NA*
- conflict list now only auto selects if there is an exact match at the top of the list
- fixed bug that forced selection to jump to 1st one in list (when there are duplicates)
> updated auto selection/fixed bug in conflict list

- client/src/components/application/Examine/CompName.vue
- client/test/jest/ComponentSnapshotTests/application/examine/__snapshots__/CompName.spec.js.snap
- client/test/unit/specs/CompName.spec.js
*Issue #: bcgov/entity#17*
*  Add tests to check whether conflicts are listed instead of nothing when there is no decision text
* . Update the decision text display to show conflicts when the (rejected) name has no decision text.
> Issue ##1157 indicate no results bcgov/entity#17

- client/src/store/index.js
- client/test/features/specs/support/given.queue.js
- client/test/unit/specs/Conflicts.spec.js
- client/test/unit/specs/ExactMatchConflicts.spec.js
- client/test/unit/specs/SynonymMatchConflicts.spec.js
- client/test/unit/specs/SynonymMatchesRequest.spec.js
*Issue #: bcgov/entity#13*
- synonymbucket call replaces special chars with '' or ' ' when required before sending to backend
- tests updated around synonymbucket
- exact match call replaces a few special chars that were breaking its search
> 13 solr synonymbucket handle special chars

- client/src/components/application/Examine/RecipeMenu.vue
- set conflicts function (which toggles the conflict recipe menu icon) was firing based on old conflict list watcher. Changed to fire off of synonym bucket or exact match
> 22 - bug fix on conflicts icon toggle

- client/src/components/application/Examine/RequestInfoHeader.vue
- client/src/store/index.js
- client/test/unit/specs/RequestInfoHeader.spec.js
*Issue #:* bcgov/name-examination#30
Preserve DRAFT state upon edit (ie: don't lose place in queue). Requires corresponding API changes to function.
> 30 - preserve DRAFT state upon edit (ie: don't lose place in queue).

- client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue
- client/src/store/index.js
- client/test/jest/ComponentSnapshotTests/application/examine/Recipe/conflicts/__snapshots__/ConflictList.spec.js.snap
- client/test/unit/specs/ExactMatchConflicts.spec.js
- client/test/unit/specs/SynonymMatchConflicts.spec.js
*Issue #:* bcgov/entity#46
UI changes to conflicts list. No rework of underlying structure (still a select element) with changes to style as far as they can go, but not as far as the desired UI would like.
> UI changes for conflicts list.

- client/src/store/index.js
- client/test/unit/specs/ExactMatchesRequest.spec.js
- client/test/unit/specs/SynonymMatchesRequest.spec.js
*Issue #:bcgov/entity#67*
- Update the urls sent to the solr query to use dollar or s for $ and cent or c for ¢, to match the indexed names.
- Update the tests
> Handle money symbols

- client/src/store/index.js
- client/test/unit/specs/SynonymMatchesData.spec.js
- client/test/unit/specs/SynonymMatchesDisplay.spec.js
we now collapse the last two stacks in the synonym bucket
> collapse last 2

- client/src/components/auth/Signin.vue
- client/src/store/index.js
- client/test/features/specs/support/clean.state.js
- client/test/unit/specs/RequestInfoHeader.spec.js
*Issue #:* bcgov/entity#86
- Retrieve the roles from keycloak when authenticating user in front end.
- Make sure they don't get permission to access anything when they aren't a **names_\*** user
> Issue #86 block non names users

- client/src/components/auth/Signin.vue
- client/src/store/index.js
- client/test/features/specs/support/clean.state.js
- client/test/unit/specs/CobrsPhoneticMatchesRequest.spec.js
- client/test/unit/specs/ExactMatchesRequest.spec.js
- client/test/unit/specs/PhoneticMatchesRequest.spec.js
- client/test/unit/specs/RequestInfoHeader.spec.js
- client/test/unit/specs/SynonymMatchesRequest.spec.js
Signed-off-by: PWEI <patrick.wei@gov.bc.ca>
*Issue #:*If a manual search with the following character, a 500 error is displayed on the screen.
- start with a slash
- colon
- end with a back slash
- unbalanced double quotes
- unbalanced single quotes
- contain @
- contain other special characters
Add a regex check to escape the special characters before sending the request to solr searches.
> Escape specail characters when send the request to solr

- client/src/components/application/Examine/CompName.vue
- client/test/unit/specs/CompName.spec.js
*Issue #:* bcgov/entity#40
Upon reset, set NR status to Draft instead of INPROGRESS.
This mainly affects re-open, as reset is forced in API call.
> Upon reset, set NR status to Draft instead of INPROGRESS.

- client/src/components/application/Examine/CompName.vue
- client/test/unit/specs/CompName.spec.js
*Issue #:*
bcgov/entity#116
Hide the Examine button from all users except examiners.
> Hide Examine button from editor users

- client/src/components/application/sections/StdHeader.vue
- client/test/unit/specs/StdHeader.spec.js
*Issue #:*
bcgov/entity#122
Hide the examine names link in the header for everyone but examiners
> Hide Examine Names link for editors

- client/index.html
- client/src/axios-auth.js
- client/src/components/application/Examine/Decision.vue
- client/src/components/application/Examine/Recipe/conditions/conditionInfo.vue
- client/src/components/application/Examine/Recipe/conflicts/ConflictInfo.vue
- client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue
- client/src/components/application/Examine/Recipe/history/historyList.vue
- client/src/components/application/Examine/Recipe/trademarks/trademarksInfo.vue
- client/src/components/application/spinner.vue
- client/src/store/index.js
- client/static/css/main.css
- client/test/features/specs/activities/select.condition.js
- client/test/features/specs/assertions/decision.screen.conditions.js
- client/test/jest/ComponentSnapshotTests/application/examine/Recipe/Trademarks/__snapshots__/TrademarksInfo.spec.js.snap
- client/test/jest/ComponentSnapshotTests/application/examine/Recipe/conflicts/__snapshots__/ConflictInfo.spec.js.snap
- client/test/jest/ComponentSnapshotTests/application/examine/Recipe/conflicts/__snapshots__/ConflictList.spec.js.snap
- client/test/jest/ComponentSnapshotTests/application/examine/Recipe/history/__snapshots__/HistoryList.spec.js.snap
- client/test/jest/ComponentSnapshotTests/application/examine/__snapshots__/Decision.spec.js.snap
- client/test/unit/specs/CobrsPhoneticMatchConflicts.spec.js
- client/test/unit/specs/ExactMatchConflicts.spec.js
- client/test/unit/specs/PhoneticMatchConflicts.spec.js
- client/test/unit/specs/SynonymMatchConflicts.spec.js
*Issue #:* bcgov/name-examination#115
Removed main page-blocking spinner from recipe steps, and replaced with call-specific spinner in various sections of recipe/exam page.
This involved breaking single conflict list into four, with four
computed lists and four sections of the template.
Also clear the lists before each call to prevent old lists showing while
new list loading.
There is also some white-space changes in ConflictList.vue (clic(), unselectPreviousSelection(), expand_collapse(), and check_deselect()) that do not change functionality.
> Removed main page-blocking spinner from recipe steps, and replaced with call-specific spinner in various sections of recipe/exam page.

- client/src/components/application/Examine/CompName.vue
- client/test/unit/specs/CompName.spec.js
*Issue #:* bcgov/entity#118
Changed RESET and RE-OPEN workflow based on role. See ticket for details. There is a corresponding backend change that is required for this to work correctly.
> Changed RESET and RE-OPEN workflow based on role.

- client/src/components/LandingPage.vue
*Issue #:* n/a
Removed manual search tips (outdated) from landing page.
> Removed manual search tips (outdated) from landing page.

- client/src/store/index.js
- client/test/unit/specs/CompName.spec.js
*Issue #:* bcgov/entity#49
Fixed bug with incorrect loading of name conflict data from api. Causing bug when NR is reset - losing conflictX_num field from name record.
> Fixed bug with incorrect loading of name conflict data from api

- client/src/store/index.js
- client/test/unit/specs/ExactMatchesRequest.spec.js
*Issue #:  [bcgov/entity#117](https://github.com/bcgov/entity/issues/117)
Put two new Regex replace name special characters logic in exactmatch query. 
- Remove all repeated + and - in the name (e.g. ++++ or -----)
- Remove ' +' or ' -' at then name of the name
> Handle 500 error when put ' +' or ' ++++' at the end of the name 

- client/src/store/index.js
- client/test/unit/specs/SynonymMatchConflicts.spec.js
*Issue #:* bcgov/entity#182
Bug fix for bad stem highlighting when single letter in name. This is actually just handling bad data (empty string) in stems list coming from API.
> bug fix - bad stem highlighting when single letter in name.

- client/src/components/application/Examine/CompName.vue
*Issue #:bcgov/entity#108*
- reset exact phrase text box on getnext, page load and new name choice
> reset exact phrase text box on getnext, page load and new name choice

- client/custom_validations/validators.js
- client/src/components/application/Examine/CompName.vue
- client/src/components/application/Examine/RequestInfoHeader.vue
- client/test/unit/specs/RequestInfoHeader.spec.js
*Issue #:bcgov/entity#126*
- added validation for name choices around 2 & 3
- jest tests added and all pass locally
> 126 edit validation fixes

- client/src/components/application/Examine/InternalComments.vue
- client/src/components/application/Examine/RequestInfoHeader.vue
*Issue #:* bcgov/entity#139
Fixed vue error (console error, not functional bug) caused by vue using comment timestamp as a conceptual key, which can have duplicates.
> #139 - fixed vue error caused by duplicate comment id as vue key

- client/src/store/index.js
*Issue #:bcgov/entity#320*
- checks if expiry date is null before reseting the hours
> fixed bug where put call to api would set expiry date if null

- client/src/components/application/Examine/Decision.vue
Fixed the action of the alt-a hotkey so that it performs the same action as the quick-approve button (ie. it clears the message in the window and approves)
> Fixed the action of the alt-a hotkey

- client/src/App.vue
- client/src/components/application/Examine/ActionButtons.vue
- client/src/components/application/Examine/CompName.vue
- client/src/components/application/Examine/RequestInfoHeader.vue
- client/test/jest/ComponentSnapshotTests/__snapshots__/App.spec.js.snap
- client/test/jest/ComponentSnapshotTests/application/examine/__snapshots__/RequestInfoHeader.spec.js.snap
- changed logic to correctly affix the "-CONSUMED" label to all NRs which are consumed.  
- When an NR is consumed, only "Get Next" and "Show Details" buttons are available.
- Same as above applies to NRs with "RESERVED", "COND-RESERVED" and "HISTORICAL" status
> entity 3976 - fix consumed status and buttons

- client/package-lock.json
- client/package.json
- client/src/components/application/Examine/RequestInfoHeader.vue
- client/src/components/application/Transactions.vue
*Issue #:* bcgov/entity#8248
* Included mapping in transaction history list for split request types.
* Applied staff comments to transactions history.
*Notes:*
* The api side of this additional `comment` property is still in code review for Namex.
> Added transactions mapping and staff comment

- client/.gitignore
- client/package-lock.json
- client/package.json
- client/src/components/application/Examine/RequestInfoHeader.vue
- client/src/store/index.js
- client/test/unit/specs/RequestInfoHeader.spec.js
Issue #: /bcgov/entity#11772
* Update getter for `consumedBy` to only return value when NR is not consumed.  Normally this is not an issue as the corp num is not populated for unconsumed NRs but Society NRs include the corp num even before the NR has been consumed.
> 11772 Update societies change of name NR consume issue

- client/src/components/application/Examine/RequestInfoHeader.vue
- client/src/store/index.js
- client/test/features/specs/support/clean.state.js
*Issue #:* https://github.com/bcgov/entity/issues/14252
1. Display refund status when NR status is REFUND_REQUESTED;
> Add refund status displaying.

- plugins/firebase.client.ts
*Issue #15225:*
This PR reduces the time it takes for the Firebase remote config cache to be invalidated down to 1 minute, so that the application banner's message can be updated more frequently.
> Fix cached application banner

- components/search/ResultsBox.vue
- components/search/ResultsControl.vue
- store/search.ts
- tests/component/SearchResultsControl.spec.ts
*Issue #18647:*
This PR implements resetting the search filters in the search results box whenever the user navigates to the search page, including when they navigate away and then come back.
> 18647 Reset search filters when navigating to the search page

- client/package-lock.json
- client/package.json
*Issue #: 18182 - Name Examination UI - Upgrade nodejs version to 20.5.1
https://github.com/bcgov/entity/issues/18182
> 18182 - Name Examination UI - Upgrade nodejs version to 20.5.1

- client/Dockerfile
*Issue #:*
*Description of changes:* to upgrade to node 20, the base image in buildconfig needs to be updated. the image in namex-fe-build was for node 16. I added a dockerfile (similar to the one from filings-ui). I updated https://console.apps.silver.devops.gov.bc.ca/k8s/ns/f2b77c-tools/buildconfigs/namex-fe-build/yaml
To deploy we no longer need to build namex-web (as the 2 build steps are merged in the Dockerfile).
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0), i.e sink for namex-fe-build is namex-front, which is used directly in deploymnetconfig.
Looks like https://namex-dev.apps.silver.devops.gov.bc.ca/home is running fine.
> dockerfile

- client/Dockerfile
*Issue #:*
*Description of changes:* decided to build source code in a separate step, as currently caddy is configured to use old s2i-caddy image (https://github.com/BCDevOps/s2i-caddy) and it will take a bit of time to figure out how to setup new configurations (since we are moving to firebase for namex ui soon, maybe not efficient use of time).
> stick with 1 step

- client/package-lock.json
- client/package.json
- client/src/components/application/Transactions.vue
*Issue #:*
https://github.com/bcgov/entity/issues/16316
Some historical data may lack proper formatting, leading to missing names in event_json. If names are missing for the 'CONSUMED' action, it causes other events not to appear on the page. In such instances, we can simply ignore this information and display other transactions and events normally.
> #16316 fix a transaction/event display bug

- client/package-lock.json
- client/package.json
- client/src/components/application/Examine/RequestInfoHeader.vue
- client/src/components/application/Examine/client/ClientInfoHeader.vue
- client/src/components/application/NameExamination.vue
- client/src/components/application/sections/StdHeader.vue
- client/src/components/auth/Signin.vue
- client/src/router/index.js
- client/src/store/index.js
- client/src/utils/utils.js
*Issue #:*
https://github.com/bcgov/entity/issues/18137
1. Allow the NR number to be displayed in the URL for examination purposes.
2. Enable users to directly modify the NR number in the URL for examination.
> 18137 Name Examination UI to reflect NR number in the URL

- client/package-lock.json
- client/package.json
- client/src/router/index.js
*Issue #:*
https://github.com/bcgov/entity/issues/19575
Name Examination Screen Blank when clicking on Examine Names tab
> 19575 hotfix: the screen blank when clicking on Exmine Names

- components/examine/recipe/compare/Item.vue
- components/examine/recipe/conflicts/ListItem.vue
- package-lock.json
- package.json
- types/index.ts
*Issue #:*
bcgov/entity#20304
This PR adds a null check to the `jurisdiction` field in `ConflictListItem`, which can sometimes be `undefined`.
> Fix conflict list occasionally not appearing

- enums/filter-dropdowns.ts
- package-lock.json
- package.json
- store/search.ts
*Issue #:*
https://github.com/bcgov/entity/issues/20067
update "Consent Required" filter in search.
Here are the meanings of the consent flags:
Null: No consent required.
R: Consent received.
N: Consent waived.
Y: Consent required.
> Update "Consent Required" filter in search

- package-lock.json
- package.json
- store/examine/index.ts
*Issue #:*
https://github.com/bcgov/entity/issues/20411
Set the last rejected name as current name choice when reset a requests with all names have been rejected.
> set the last rejected name as current name choice

- components/ListSelect.vue
- components/examine/decision/select/Conditions.vue
- components/examine/decision/select/Conflicts.vue
- components/examine/decision/select/Macros.vue
- components/examine/decision/select/Trademarks.vue
- package-lock.json
- package.json
*Issue #:*
bcgov/entity#20340
This PR automatically closes `ListSelect` components with the `multiple` prop passed in when an option is selected/deselected.
> 20340 Close decision dropdowns when an option is selected

- components/examine/names_list/index.vue
*Issue #:* https://github.com/bcgov/entity/issues/20796
*Description of changes:* Name Examination UI - Transactions page name list has incorrect order
> Transactions page name list has incorrect order

- components/examine/recipe/conflicts/ListItem.vue
- package-lock.json
- package.json
*Issue #:21000*
Fixed the accordion text which was not drag selectable by setting `user-select: text` property in styles. 
> Fix: Allow Accordion Text Selection and Copy in Exact Word Order + Synonym Match 

- store/examine/index.ts
*Issue #: 20887
Since we use ISO while displaying transaction, I converted datetime format from UTC to ISO.
[This](https://github.com/bcgov/namex/pull/1533) PR contains the changes on the backend(namex) side.
> Changed date formation from UTC to ISO

- util/date.ts
*Issue #: 20887*
- Updated `/utils/date.ts/TIMESTAMP_FORMAT` to include space between time and "AM/PM".
> Added Space Between Time and "AM/PM"

- components/examine/request_info/Status.vue
…is instead the username of examiner logged in
*Issue #:*
Made the examiner a computed property that displays the current examiner if it is one of the defaults. This change ensures that the examiner's name is shown only for display purposes and is not saved. This way, an examiner can view a ticket without editing it, keeping the ticket in 'open' status and allowing another examiner to claim it later with their own name.
> For NRs in draft status that have not been edited. Made examiner name display as current examiner

- components/search/ResultsBox.vue
- package-lock.json
- package.json
- store/search.ts
*Issue #: [20339](https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/20339)
Implemented Local Storage to persist dropdown filter status.
> 20339 - implemented local storage to store dropdown filter status

- .github/workflows/e2e.yml
> Changed url to not be mandatory. Trying to get Cypress Github action smoke tests to work

- app/package-lock.json
- app/package.json
- app/store/examine/index.ts
remove the redundant code when updating nr state from draft to inprogress
*Issue #:*
[21593](https://github.com/bcgov/entity/issues/21593)
NR states updated twice when UpdateNRState, which causing screen flash. Removed one.
> remove the redundant code when updating nr state to inprogress

- app/components/examine/recipe/tabs/Header.vue
- app/package-lock.json
- app/package.json
- app/store/examine/conflicts.ts
- app/store/examine/index.ts
*Issue #:* https://github.com/bcgov/entity/issues/20999
- Examiners should now be able to toggle auto add checkbox for automatically adding potential conflicts or not
> 20999 - Conflicts Auto Add Checkbox Btn Refactor

- app/package-lock.json
- app/package.json
- app/store/examine/conflicts.ts
*Issue #:* https://github.com/bcgov/entity/issues/20999
With [Initial PR](https://github.com/bcgov/name-examination/pull/1477), users were able to modify the automatically selected conflict lists with `auto add` checked on and this would persists. With these changes, the automatically selected conflict lists would remain immutable but users can uncheck `auto add` and then make their selections.
> 20999 - Auto Add Fix: Make Initial Conflicts List Immutable

- app/components/app_header/index.vue
- app/package.json
- app/store/search.ts
- app/util/constants.ts
- app/util/index.ts
*Issue: [20339](https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/20339)*
Persist `Priority Toggle` Status
> 20339-Persist Priority Queue Toggle

- app/components/examine/request_info/Status.vue
- app/package.json
- app/store/transactions.ts
*Issue #:* https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/22015
- Made it so when examining an NR. If the examiner field is not an IDIR it searches for the last IDIR username in transactions table. If an IDIR is not found it keeps the examiner field as is, else updates the examiner field. 
> 22015 displaying wrong examiner name

- app/components/app_header/index.vue
- app/enums/filter-dropdowns.ts
- app/package.json
- app/store/examine/options.ts
- app/store/search.ts
- app/util/constants.ts
- app/util/index.ts
*Issue #:* 22308
https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/22308
Integrated storing and retrieving variables from local storage with the Vue Store better. Previously it was only using local storage but the request used the Vue Store, meaning when queue was toggled requests still came in with the queue set as true. 
To do this some types had to be defined to properly retrieve the value from storage as the correct type. Also the other dropdowns had to be slightly modified.
**The queue toggle will only work in Test and Prod**
- For some reason the queue does not work in dev, currently it never picks up NRs of priority while test always picks up NRs of priority. This means it will have to be tested in test …
> 22308 fix priority queue toggle

- app/components/search/ResultsBox.vue
- app/enums/filter-dropdowns.ts
- app/package.json
- app/store/search.ts
- app/util/index.ts
Issue #: 22308
https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/22395
Description of changes:
Cleaned up code I added in my last PR which was made quickly as a hot-fix. https://github.com/bcgov/name-examination/pull/1485.
The enums were only used for mapping so got rid of them and added the default values directly when initializing the store.
Also stringified the search column values before storing in local storage so it is consistent with how everything else is stored in local storage. This made the catch block if clause when retrieving values from local storage redundant so that was removed as well.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the …
> 22308 clean up local storage access

- app/package.json
- app/store/examine/index.ts
Issue #: https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/21893
Description of changes:
- Added a try-catch block to the update function.
- Removed unnecessary fetchAndLoadNr() calls as that method is already called in updateRequest()
> 21893 Catch errors when updating NR data

- app/components/PriorityLabel.vue
- app/components/app_header/index.vue
- app/components/examine/decision/Header.vue
- app/package.json
- testing/cypress/constants.ts
- testing/cypress/e2e/smoke/smoke-20-approvals.cy.ts
- testing/cypress/e2e/smoke/smoke-60-priorityqueue.cy.ts
- testing/cypress/pageObjects/examinePage.ts
- testing/cypress/pageObjects/homePage.ts
*Issue #:*
Relates to https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/22417
The rejections test was flakey based on number of names per NR so needed to be fixed.
- Changed rejections to assert PUT requests instead of PATCH requests
- Added a test for conditional approval
- Added tests for the priority queue
> 22417 fix flakey smoke tests

- app/components/app_footer/VersionInfo.vue
- app/package.json
- testing/cypress/appActions/Utilities.ts
- testing/cypress/pageObjects/homePage.ts
*Issue #:*
- Fixed how the UI gets the API version number. Instead of always getting the version number of dev api it gets the version number of whatever API it is pointing at. 
- Also corrected the check for the current date on the home page for the E2E cypress testing. 
> 23752 namex version not picked up correctly

- app/components/examine/recipe/match/BCCorp.vue
- app/components/examine/recipe/match/XproCorp.vue
- app/components/examine/recipe/match/index.vue
- app/package.json
- app/store/examine/conflict-data.ts
- app/types/index.ts
*Issue #:*
https://github.com/bcgov/entity/issues/24298
Ensure no errors occur even when conflict corp information is empty
> #24298 Ensure no errors occur even when conflict corp information is empty.

- app/package.json
- app/store/examine/index.ts
- testing/cypress/pageObjects/examinePage.ts
*Issue #:* https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/22784
**Problem**: When a Name Request (NR) is approved, an unnecessary second patch request is sent, leading to a 401 error. This happens because the `currentNameChoice` is incorrectly set to undefined during the approval process.
**Solution**: Removed the code that sets the `currentNameChoice` to undefined from the `parseNr` method in the Examine Store. 
**Detailed Explanation** 
- Upon NR approval via `makeDecision(APPROVED)`, the `pushDecision(APPROVED)` and subsequently `updateNRState(APPROVED)` are triggered. [Code Reference](https://github.com/bcgov/name-examination/blob/main/app/store/examine/index.ts#L632)
- This sequence leads to …
> 22784_fix_401_response_on_nr_approvals

- app/data/request_type_rules.json
- app/data/request_types.json
- app/enums/codes.ts
- app/package-lock.json
*Issue #: 24255
1) Added missing type: BECC - Benefit Company -> Community Contribution Company 
2) ULCB duplicated and removed one of them (Unlimited Liability Company to BC Limited Conversion)
> Name Examination UI: need to update NR request types#24255

- app/store/examine/conflict-data.ts
*Issue #:*
https://github.com/bcgov/entity/issues/24298
This is an update to the previous code change: the section for retrieving conflict business info from Entities has been commented out because:
1. The corp number from Solr query result is in the COLIN format (without the BC prefix).
2. The business query does not provide office and party information.
> #24298 Name-Examination UI - error occurred when selecting conflict or conflict selection has values

- app/components/app_footer/VersionInfo.vue
- app/package.json
*Issue #:* https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/23752
Nuxt3 does not expose environment variables directly for security reasons which was causing this method to fail and default to the dev configuration. 
This PR makes use of the runtime config to get these environment variables instead that are defined here:
https://github.com/bcgov/name-examination/blob/main/app/nuxt.config.ts#L43
Also this PR gets rid of the default values so when it does not work it is obvious and does not potentially give the 'wrong version'.
> 23752 use runtime config when fetching namex version

- app/package.json
Version Number was not bumped in https://github.com/bcgov/name-examination/pull/1560 (Keycloak Upgrade fix PR)
- This PR bumps the version number so 1.2.40 can be released to prod instead of releasing 1.2.39 on top of 1.2.39
> 26228 bump version number to 1.2.40

- app/components/examine/decision/RequestorMessage.vue
- app/package.json
*Issue #:*
*Description of changes:*  Fixed the issue that the selected items from Conditions, Conflicts, Macros, or Trademarks are not pop up on the "Message To Requestor" box.
> 26816-Conditions are not being populated in Message to Requestor Field

- app/data/request_types.json
- app/package.json
*Issue #:* https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/entity/21053
https://github.com/bcgov/entity/issues/21053
When a new Society is created they correctly have the Entity Type Code and Request Action Code in NameX DB. 
The problem occurs (entity type code set to null) when the NR is updated in Name-Examination UI. 
- The `updateRequest()` fires which calls `getNrData()` which updates the `entity_type_code` based on the `requestTypeObject`
https://github.com/bcgov/name-examination/blob/main/app/store/examine/index.ts#L371
- The problem is that the `requestTypeObject` for Societies do not have this `entity_type_cd` so it becomes null on the UI which updates the database to also be null
This PR adds the missing …
> 21053 fix entity type codes for new society nrs becoming null

- .github/workflows/ci.yml
- app/components/app_footer/VersionInfo.vue
- app/package.json
- app/util/namex-api.ts
*Issue #: https://github.com/bcgov/entity/issues/26502
Calls to NameX API include app-name header. 
- All calls to NameX API go through the `callNamexApi` method. So the app-name was added here which was retrieved from the package.json file
- There was a call to NameX API to get the version number that did not go through `callNamexApi`, so that was changed to make it so that it does for consistency.
> 26502 calls to namex api include app-name header

- app/store/examine/conflicts.ts
- app/store/examine/index.ts
*Issue #:*
https://github.com/bcgov/entity/issues/29880
Retrieve history data from get conflicts query
> 29880 Retrieve history data from get conflicts query
