ISSUE_TEMPLATE.md
Updated the template to reflect the details required for EPICS, Stories, Scenarios and Tasks.  These have been selected as the issue types we will use to manage the work in zenHub.
=> Updated To Reflect Agreed Upon Issue Types

ISSUE_TEMPLATE.md
Corrected mark-up error on EPIC title.
=> Corrected MD Error

ISSUE_TEMPLATE.md
Update dthe styling to improve visual appearance and workflow.
=> Updated the Styling in the Template

ISSUE_TEMPLATE.md
Changed Acceptance Criteria Completed to Acceptance Criteria Defined.
=> Updated Language in the Template

Jenkinsfile, name-examination/HelloWorld.py
* Update Jenkinsfile
* playing with python
=> Updates to include hello world (#1)

client/.s2i/bin/assemble
Added assemble file to s2i directory to try to get npm to build front-end code during chain build.  Issue #232
=> s2i assemble file for fe npm build

Jenkinsfile
took out "nodes" tag.  Didn't work.
=> Working on chain build jenkinsfile.  Issue #232

functional-tests/src/test/groovy/modules/ManualsMenuModule.groovy, functional-tests/src/test/groovy/pages/GebishOrgHomePage.groovy, functional-tests/src/test/groovy/specs/sampleSpec.groovy
=> BDD Samples

jenkinsFileBDD
Separatre BDD jenkins piepline
=> BDD  Jenkins Pipeline

client/package.json, client/src/components/dropdown/Search/NameMatches.vue
=> Remove pop-up/update webpack

client/build/utils.js, client/src/components/dropdown/Search/NameMatches.vue, client/src/components/dropdown/Search/RequestInfo.vue
=> Fix webpack bug

client/src/components/dropdown/Search/RequestInfo.vue, client/src/components/dropdown/SearchResults.vue
=> Component elimination

client/src/components/dropdown/Search/NameMatches.vue, client/src/components/dropdown/SearchResults.vue
uncommented the requestviewinfo component
=> Add requestinfoview

client/index.html, client/src/components/application/sections/StdHeaderOld.vue, client/src/components/dropdown/Search/ExaminationMenu.vue, client/src/components/landing/auth/Signin.vue, client/src/components/landing/auth/keyCloak.vue, client/src/router/index.js, client/src/store/index.js, client/static/config.json, client/static/js/keycloak.js, client/static/keycloak.json, client/static/keycloakLocal.json
=> KeyCloak Login and API Connectivity test

client/src/components/application/sections/StdHeader.vue, client/src/components/landing/auth/Signin.vue, client/src/components/landing/auth/keyCloak.vue, client/src/store/index.js
=> Fix Uri _redirect

Jenkinsfile, openshift/templates/namex-web-bc.tools.json, openshift/templates/namex-web-caddy-config.dev.json, openshift/templates/namex-web-caddy-config.test.json, openshift/templates/namex-web-dc.dev.json, openshift/templates/namex-web-dc.test.json, openshift/templates/namex-web-int-bc.tools.json, openshift/templates/namex-web-route.dev.json, openshift/templates/namex-web-route.test.json, openshift/templates/namex-web-service.dev.json, openshift/templates/namex-web-svc.test.json
=> updated deploys for dev->test pipeline

client/src/components/application/sections/StdHeader.vue, client/src/components/dropdown/Find.vue, client/src/components/dropdown/Find/findFilter.vue, client/src/components/dropdown/Search/CompName.vue, client/src/components/dropdown/Search/IssueInfo.vue, client/src/components/dropdown/Search/NameMatches.vue, client/src/components/dropdown/Search/conflicts/ConflictInfo.vue, client/src/components/dropdown/Search/conflicts/ConflictList.vue, client/src/components/dropdown/Search/conflicts/conflictInfoType/corpMatch.vue, client/src/components/dropdown/Search/conflicts/conflictInfoType/namesMatch.vue, client/src/router/index.js, client/src/store/index.js
=> Directory restructure

client/src/components/Decision.vue, client/src/components/application/Examine/CompName.vue, client/src/store/index.js
Fixed bug - missing currentNameObj functionality; also improvements to decision workflow.
=> Fixed bug - missing currentNameObj functionality.

client/src/components/application/Examine/CompName.vue, client/src/components/application/Examine/IssueInfo.vue, client/src/components/application/Examine/NameMatches.vue, client/src/components/application/Examine/Recipe/conditionRecipe.vue, client/src/components/application/Examine/Recipe/history/historyInfo.vue, client/src/components/application/Examine/Recipe/history/historyList.vue, client/src/components/application/Examine/Recipe/historyRecipe.vue, client/src/components/application/Examine/Recipe/trademarks/trademarksInfo.vue, client/src/components/application/Examine/Recipe/trademarks/trademarksList.vue, client/src/components/application/Examine/Recipe/trademarksRecipe.vue, client/src/components/application/Find/findFilter.vue
=> recipe restructure 

client/src/components/application/Find/findFilter.vue, client/src/store/index.js
Can filter with priority and limit/offset
=> search table beginning #538

.github/PULL_REQUEST_TEMPLATE.md
*Issue #:* #612 
*Description of changes:* Adding a template to be filled out for pull requests.
=> closing #612

client/src/components/Decision.vue, client/src/components/application/Examine/CompName.vue, client/src/components/application/Examine/Recipe/conditions/conditionInfo.vue, client/src/components/application/NameExamination.vue, client/src/store/index.js
#584 Decision changes and fixes, plus message to examiner about in-progress NR ownership.
*Issue #:* #584 
- revised Conditions in examine and decision screens to handle internal alerts vs. customer instructions
- added messaging to examiner re. NR in progress but owned by someone else
- added conditional text on Accept button re. consent required
Issue still in progress after this pull requests - more changes to be made.
=> 584 decision changes and bug fixes

client/src/components/application/Examine/CompName.vue
*Issue #:* 562
*Description of changes:* Added the Hold button for name requests.
=> Added front-end button to put name request on Hold - #562

client/src/components/application/NameExamination.vue
*Issue #:* #611 
Added alert re. previous name requests from history. 
This pull requests closes the issue.
=> #611 Added alert re. previous name requests from History.

client/src/components/application/Find/findFilter.vue, client/src/store/index.js
-> search table functions - minor changes to come
-> can select an NR and load it into the examine screen - no backend work was needed
=> Search name requests front-end #607 #606 #579

client/src/components/application/Examine/InternalComments.vue, client/src/components/application/Examine/RequestInfoHeader.vue, client/src/components/application/Examine/nwpta/nwpta.vue, client/src/store/index.js
*Issue #:* #591 
NR Details: added nwpta plus minor layout changes.
=> NR Details: added nwpta plus minor layout changes.

client/src/components/application/Examine/CompName.vue, client/src/store/index.js
=> Add Fast Path approval/reject - and manual search

client/src/components/application/Examine/CompName.vue
=> Fix errant colon/ hide fast path buttons when needed

client/index.html, client/src/axios-auth.js, client/static/css/main.css
*Issue #:* #655 
Added loading spinner for longer-running ajax requests. 
=> Added loading spinner for longer-running ajax requests.

client/index.html, client/src/App.vue, client/src/axios-auth.js, client/src/components/application/Examine/InternalComments.vue, client/src/components/application/Examine/RequestInfoHeader.vue, client/src/store/index.js, client/static/config/configuration.json
=> base URL config load

client/src/components/application/Examine/RequestInfoHeader.vue, client/src/components/application/Examine/client/ClientInfoHeader.vue, client/src/store/index.js, client/static/js/utils.js, client/static/ui_dropdowns/request_type_rules.csv
*Issue #:* #582 
Added request type edit rules and validation using vuelidate.
Simple 'required' validation, plus accuracy check on Previous NR and Corp Num.
Additional Info built from template based on request type.
=> Added request type edit rules and validation using vuelidate.

client/static/ui_dropdowns/requesttype.json
=> Changed sort order for request type dropdown per Alan.

client/src/components/application/Examine/CompName.vue, client/static/css/main.css
*Issue #:* n/a
Misc bug fixes:
- only show Get Next button when appropriate
- UI changes to manual search
- changed secondary (grey) buttons to orange
=> Misc bug fixes

client/src/components/application/Examine/CompName.vue, client/src/components/application/Examine/InternalComments.vue, client/src/components/application/Examine/RecipeMenu.vue, client/src/components/application/Examine/RequestInfoHeader.vue, client/src/components/application/Find/findFilter.vue, client/src/components/application/sections/StdHeader.vue
*Issue #:* n/a
Added ids and classes for identification in Selenium tests.
=> Added ids and classes for identification in Selenium tests.

Jenkinsfile
*Issue #:* n/a
Added myself to Jenkins file for deploying to test.
=> Added myself (Katie) to Jenkins file for deploying to test.

client/src/components/application/Examine/NameMatches.vue
=> Removed trademark sign.

client/src/components/application/Examine/CompName.vue, client/src/store/index.js
=> reset furnished feature added #520

client/src/components/application/Examine/CompName.vue
*Issue #:* #720 #721 
Fixed bug with fast path messages - assign directly, do not use stack.
Also fixed minor bug with aproved-expired status flag.
=> Fixed bug with fast path messages

client/src/components/application/Examine/client/ClientInfoHeader.vue
*Issue #:* #718 
Removed required validation on NR applicant info; added max lengths. Supports/related to bug fix in backend, and satisfies business request to remove "required" validation on contact info fields.
=> Removed required validation on NR applicant info; added max lengths.

client/src/components/application/Examine/RequestInfoHeader.vue, client/src/store/index.js, client/static/ui_dropdowns/jurisdiction 1.json, client/static/ui_dropdowns/jurisdiction 2.json
*Issue #:* #692 
Changes to jurisdiction: sorting countries, using full names.
=> Changes to jurisdiction: sorting countries, using full names.

client/src/components/application/Find/findFilter.vue
This will make search work again in dev -- push to test at the same time as the namex-api
=> search update to match backend update

client/src/axios-auth.js, client/src/store/index.js
=> error handling - axios interceptor, errorJSON in store

client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue, client/src/components/application/Find/findFilter.vue, client/src/components/application/NameExamination.vue
logout banner flash fixed & conflict details refresh fixed
=> Bug fixes #726 & #646

client/src/components/application/Examine/CompName.vue
=> Shortcut keys

client/src/components/application/Examine/RequestInfoHeader.vue
*Issue #:* n/a
Bug fixes in NR Header save:
1. error when no nwpta components on screen.
2. error when Additional Info is null.
=> Bug fixes in NR Header save

client/src/components/application/Examine/Decision.vue, client/src/components/application/Examine/InternalComments.vue, client/src/store/index.js
*Issue #:* #686 
Comments in decision - fixed so it adds to name record and is sent to API.
=> Comments in decision - fixed so it adds to name record and is sent to API

client/src/components/application/Examine/CompName.vue
*Issue #:* #777 
Clear all decision data upon re-open. Also fixed bug w. missing icon for conditionally approved names.
=> Clear all decision data upon re-open

client/src/components/application/Find/findFilter.vue
- very small data refactor to match other components
- fixed comments bug that caused search state to be blank & mess up state values
- fixed search by cancelled state error
=> search table bug fix

client/src/components/application/Find/findFilter.vue
*Issue #:* n/a
Added bootstrap styling to search form fields.
=> Added bootstrap styling to search form fields.

client/src/components/application/Examine/Recipe/history/historyList.vue
=> history colour logic fix

client/src/components/LandingPage.vue, client/src/components/application/Examine/CompName.vue, client/src/components/application/sections/StateHeader.vue, client/src/components/application/sections/StdHeader.vue, client/src/components/auth/Signin.vue, client/src/router/index.js, client/src/store/index.js
=> Hoe page statistics / GetNext bug fix

client/src/components/auth/Signin.vue, client/src/router/index.js
=> Login Bug Fixes

client/.gitignore
wont work unless you untrack the files or renew your clone repository
=> git ignore keycloak dir

client/src/components/LandingPage.vue, client/src/store/index.js
=> Home page statistics - bug fix

client/src/components/LandingPage.vue
=> Stats bug - final fix

client/src/components/LandingPage.vue, client/src/components/application/sections/StdHeader.vue
=> Fix NR Load / Home page text

client/src/store/index.js
=> error msg update for 404 on NR conflict

client/src/components/LandingPage.vue
*Issue #:* n/a
Minor homepage layout changes.
=> Minor homepage layout changes.

client/src/components/application/Examine/InternalComments.vue, client/src/components/application/Examine/Recipe/conflictRecipe.vue, client/src/components/application/Examine/Recipe/conflicts/conflictInfoType/namesMatch.vue, client/src/components/application/Examine/Recipe/history/historyInfo.vue, client/src/components/application/Examine/Recipe/historyRecipe.vue, client/src/components/application/Examine/RequestInfoHeader.vue, client/src/components/application/Find/findFilter.vue, client/src/store/index.js
*Issue #730 :*
Front-end converts expiry/submitted/lastUpdate dates to local timezone for display -- saved data maintains UTC format
=> timezone bug-fix

client/src/components/application/Examine/RequestInfoHeader.vue, client/src/components/application/Examine/nwpta/nwpta.vue, client/src/store/index.js, client/static/js/utils.js
*Issue #:* #938 
Added edit functionality for Expiry Date; optimized validation code between nr details and nwpta; fixed bug enabling validation on un-editable fields when editing furnished.
=> Added edit functionality for Expiry Date

client/index.html
=> Added cache breaker to utils.js.

client/src/components/application/Examine/CompName.vue, client/src/components/application/Examine/RequestInfoHeader.vue, client/src/store/index.js
*Issue #:* #937 
Added CANCEL functionality.
=> Added CANCEL functionality.

client/src/components/application/Examine/RequestInfoHeader.vue
*Issue #:* #931 
Fixed bug - nwpta_required check not happening often enough.
=> Fixed bug - nwpta_required check not happening often enough.

client/src/components/application/Examine/CompName.vue
*Issue #:* n/a
Renamed cancel button 'Cancel Request' to prevent confusion w. decision cancel button.
=> Renamed cancel button 'Cancel Request' to prevent confusion w. decision cancel button.

client/src/components/application/Examine/CompName.vue
*Issue #:* n/a
Cancel NR button chgs - hide on decision screen; change to "Cancel Request" on popup.
=> Cancel NR button chgs - hide on decision screen; change to "Cancel Request" on popup.

client/src/components/application/Examine/RequestInfoHeader.vue, client/src/components/application/Examine/nwpta/nwpta.vue, client/src/store/index.js, client/static/js/utils.js, client/static/ui_dropdowns/request_type_rules.csv
*Issue #:* #958 #931 
Handle do-it-for-me nwpta requests differently (#958); fix bug re. req type rules (#931).
=> Handle do-it-for-me nwpta requests differently (#958); fix bug re. req type rules (#931)

client/src/components/application/Examine/RequestInfoHeader.vue
*Issue #:* #985 
bug fix - js error when nwpta components not present.
=> bug fix - js error when nwpta components not present.

client/src/components/application/sections/StdHeader.vue
*Issue #:* #972 
Trim spaces off search (NR search box in header).
=> Trim spaces off search (NR search box in header).

client/Jenkinsfile
*Issue #923:*
added option to run pipeline even if there are no changes
=> pipeline update

client/package.json, client/test/e2e/specs/test.js, client/test/unit/jest.conf.js, client/test/unit/specs/LandingPage.spec.js
*Issue #:*
NA
Fix the base tests to start from a green state
=> Tests are back to green

client/src/components/application/Examine/CompName.vue, client/src/components/application/Examine/Recipe/conditionRecipe.vue, client/src/components/application/Examine/Recipe/conflictRecipe.vue, client/src/components/application/Examine/Recipe/conflicts/ConflictInfo.vue, client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue, client/src/components/application/Examine/Recipe/history/historyInfo.vue, client/src/components/application/Examine/Recipe/historyRecipe.vue, client/src/components/application/Examine/RecipeMenu.vue, client/src/components/application/Examine/client/ClientInfo.vue, client/static/css/main.css, docs/DeveloperSetupAndRun.md
*Issue #: #1000  *
- Updated the scoped style for p, h3, and h2 tags within the examination section.
- Updated the styles/font-sizes of the Requested name and optional names.
- Updated the font size in the search field, and the font size of the search icon.
- Updated proportionally the "Recipe" buttons, their icons, and the size of the right arrow.
=> Issue 1000 increase fontsize

client/src/components/application/Examine/CompName.vue, client/src/components/application/Examine/Recipe/conflictRecipe.vue, client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue, client/src/components/application/Examine/Recipe/history/historyList.vue, client/src/components/application/Examine/Recipe/historyRecipe.vue, client/src/components/application/Examine/RecipeMenu.vue, client/src/components/application/Find/findFilter.vue
*Issue #:* #1006 
UI changes to recipe steps and conflict/history readability; also increased size of manual search font and search screen filter box.
=> UI changes to recipe steps and conflict/history readability

client/src/components/application/Examine/RequestInfoHeader.vue, client/src/components/application/Examine/nwpta/nwpta.vue
*Issue #1002:*
A couple rule changes around displaying newpta info + some div/padding re-arrangement for display
=> nr details banner shrunk #1002

client/src/components/application/Examine/CompName.vue, client/src/components/application/Examine/RequestInfoHeader.vue
*Issue #: #1001 *
Update the hotkeys on the Decision pane, "Cancel" becomes "Ba*c*k" and alt keys are added for Back, Reject, Approve.
=> Issue #1001: Add more keyboard shortcuts, and change 'Cancel' to 'Back'

client/src/components/application/Examine/CompName.vue, client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue, client/src/components/application/Examine/Recipe/history/historyList.vue, client/src/components/application/Examine/RecipeMenu.vue
*Issue #1005:*
tabindex order change on the examination screen.
=> tabindex ordering update #1005

client/test/unit/specs/StdHeader.spec.js
=> Secure the fix of the NR space suffix described in Issue #962

client/test/unit/specs/StdHeader.spec.js
Note that the skipped tests are potential bugs. 
Please review
=> StdHeader coverage increased

client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue, client/src/components/application/Examine/Recipe/history/historyList.vue
*Issue #:* n/a
Increased size of conflict/history lists per John and Kaine.
=> Increased size of conflict/history lists per John and Kaine.

client/src/components/application/Find.vue, client/test/unit/specs/StdHeader.spec.js
**to be reviewed by Eric**
*Issue #:* n/a
Updated header jest tests:
- changed logout tests to reflect UI
- unskipped /find test
=> Updated header jest tests

client/src/components/application/Examine/RequestInfoHeader.vue, client/src/components/application/sections/StdHeader.vue, client/test/unit/specs/StdHeader.spec.js
*Issue #:* #1029 
Revised header UI per #1029.
=> Revised header UI per #1029.

client/test/unit/specs/CompName.spec.js, client/test/unit/specs/ConditionRecipe.spec.js, client/test/unit/specs/LandingPage.spec.js, client/test/unit/specs/StdHeader.spec.js
*Issue #1035 :*
- jest tests added for restricted words
- eslint-disable added in for other 'spec' tests for better readability
=> jest tests added for conditions recipe

client/src/App.vue, client/src/components/LandingPage.vue, client/src/components/application/sections/StdHeader.vue, client/static/css/main.css, client/test/unit/specs/LandingPage.spec.js, client/test/unit/specs/StdHeader.spec.js
*Issue #:* #1029 
Header UI improvements, to match gov standard.
=> Header UI improvements, to match gov standard.

client/Jenkinsfile
*Issue #:*
- katie + walter now have permissions throughout pipeline
- if statement for proceeding with the pipeline on 'no changes' reversed for better readability
=> pipeline update (permissions/logic change)

client/package.json, client/test/features/conditional.approval.feature, client/test/features/specs/activities/assertions.decision.screen.js, client/test/features/specs/activities/assertions.nr.status.js, client/test/features/specs/activities/given.assigned.nr.requiring.consent.js, client/test/features/specs/activities/given.restricted.word.js, client/test/features/specs/activities/index.js, client/test/features/specs/activities/when.accessing.conditions.tab.js, client/test/features/specs/activities/when.accessing.name.examination.js, client/test/features/specs/activities/when.approving.with.condition.js, client/test/features/specs/activities/when.going.to.decision.screen.js, client/test/features/specs/activities/when.selecting.condition.js, client/test/features/specs/conditional.approval.spec.js, client/test/features/specs/quick.approve.spec.js, client/test/features/specs/support/api.stubs.js, client/test/unit/setup.js
*Issue #:*
Feature test documenting approval with one condition
=> Joe can approve with condition

client/src/components/application/sections/StdHeader.vue
*Issue #:*
link added in the navbar to get examiners to the solr-admin-app from Namex
=> admin link in navbar added

client/src/components/application/Stats/Stats.vue, client/src/components/application/sections/StdHeader.vue, client/src/router/index.js
*Issue #:* #1057 
Added reporting/stats for senior examiners to use during reviews.
=> Added reporting/stats for senior examiners to use during reviews.

client/src/components/application/sections/StdHeader.vue, client/static/css/main.css
*Issue #:* #1029 
Header UI changes.
=> Header UI changes.

client/src/components/application/Examine/RequestInfoHeader.vue
*Issue #:* #975
Removed restriction on show/hide nwpta based on req type.
=> Removed restriction on show/hide nwpta based on req type.

client/src/components/application/Examine/CompName.vue
*Issue #1087:*
- RESET now clears decisions on all 3 names (if there are 3)
=> fixed reset bug on 3 names

client/src/components/application/Examine/RequestInfoHeader.vue, client/test/unit/specs/RequestInfoHeader.spec.js
*Issue #1042:*
- this pr includes tests surrounding the requestInfoHeader/edit component 
- all Jest tests added pass
- more tests should be added to test this component fully
Skipped tests:
- cancel/save testing (not working properly)  
=> jest tests for requestInfoHeader

client/src/components/application/Examine/Recipe/conflicts/conflictInfoType/namesMatch.vue, client/src/components/application/Examine/Recipe/history/historyInfo.vue, client/test/jest/ComponentSnapshotTests/application/examine/Recipe/conflicts/conflictInfoType/NamesMatch.spec.js, client/test/jest/ComponentSnapshotTests/application/examine/Recipe/conflicts/conflictInfoType/__snapshots__/NamesMatch.spec.js.snap
*Issue #:* #1078 
Added decision text and conflicts to recipe steps conflicts/history NR view.
=> Added decision text and conflicts to recipe steps conflicts/history NR view.

client/test/unit/specs/RequestInfoHeader.alert.spec.js
*Issue #:*
Add tests to describe the alert when deleting first name choice in edit mode
=> RequestInfoHeader alerts when first name is missing

client/src/components/application/Examine/Decision.vue, client/test/unit/specs/Decision.spec.js
*Issue #:* #1076 
Adjust conflict message (customer decision text) when consent required.
=> 1076 conditional conflicts

client/src/components/application/Stats/Stats.vue, client/test/jest/ComponentSnapshotTests/application/stats/__snapshots__/Stats.spec.js.snap
*Issue #: #1081 *
- Added a paging component above the table
- Used the b-table component
- Updated the first column to use the previous formatting of details such as comments, names, status etc.
=> Issue #1081 stats timeout

client/src/components/application/Examine/Decision.vue, client/test/unit/specs/Decision.spec.js
*Issue #:* bcgov/name-examination#1076
Fixed bug related to conflicts and consent.
=> Fixed bug related to conflicts and consent.

client/src/components/application/Examine/RequestInfoHeader.vue
*Issue #:* #1151 
Added comments indicator on NR Details.
=> Added comments indicator on NR Details.

client/src/components/application/Examine/CompName.vue, client/test/jest/ComponentSnapshotTests/application/examine/__snapshots__/CompName.spec.js.snap, client/test/jest/ComponentSnapshotTests/application/stats/__snapshots__/Stats.spec.js.snap, client/test/unit/specs/CompName.spec.js
*Issue #:*
*Description of changes: update the stats snapshot*
=> Update stats snapshot

client/src/components/application/Find/findFilter.vue
*Issue #:NA*
added completed option on state filter for search page
- should go up with backend
=> completed filter added on search

client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue, client/src/components/application/Examine/RecipeMenu.vue, client/src/store/index.js
*Issue #NA:*
Synonym bucket added on conflict list for solr search
- MUST go up AFTER backend 
=> synonym bucket added for solr search

client/src/store/index.js, client/test/features/specs/support/given.queue.js, client/test/jest/ComponentSnapshotTests/application/examine/Recipe/conflicts/__snapshots__/ConflictList.spec.js.snap, client/test/unit/specs/Conflicts.spec.js, client/test/unit/specs/ExactMatchConflicts.spec.js, client/test/unit/specs/ExactMatchesRequest.spec.js
*Issue #:*
test now simpler to read ( I hope )
=> the documentation of the /exact-match call is now leaner

client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue, client/test/unit/specs/ExactMatchConflicts.spec.js
*Issue #:*
providing a stub for company info
provide the missing index field in selected conflict to prevent triggering undefined selection
=> less error messages in console

client/src/store/index.js, client/test/features/specs/support/given.queue.js, client/test/unit/specs/Conflicts.spec.js, client/test/unit/specs/ExactMatchConflicts.spec.js, client/test/unit/specs/SynonymMatchConflicts.spec.js, client/test/unit/specs/SynonymMatchesRequest.spec.js
=> 13 solr synonymbucket handle special chars

client/src/components/application/Find/findFilter.vue, client/src/store/index.js, client/test/jest/ComponentSnapshotTests/application/find/__snapshots__/FindFilter.spec.js.snap, client/test/unit/specs/Conflicts.spec.js, client/test/unit/specs/ExactMatchConflicts.spec.js, client/test/unit/specs/ExactMatchesRequest.spec.js, client/test/unit/specs/SynonymMatchConflicts.spec.js
- search page filter added for last update
- garbage bucket in manual search call deleted
- tests updated
=> last update filter add + garbage bucket deleted

client/src/components/application/Examine/Decision.vue, client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue, client/src/store/index.js, client/test/features/specs/assertions/decision.screen.conditions.js, client/test/features/specs/support/api.stubs.js, client/test/features/specs/support/clean.state.js, client/test/jest/ComponentSnapshotTests/application/examine/__snapshots__/Decision.spec.js.snap, client/test/unit/specs/Decision.spec.js
- changed initialization + logic for conflictList in decision.vue
- updated jest tests to secure it
=> bug fix for decisions with tests

client/src/store/index.js
- pass current hour back in search to solve timezone issue with date filters
=> pass current hour back to api

client/src/components/application/Examine/Decision.vue, client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue, client/src/components/application/Find/findFilter.vue, client/src/store/index.js, client/test/features/specs/assertions/decision.screen.conditions.js, client/test/features/specs/support/api.stubs.js, client/test/features/specs/support/clean.state.js, client/test/jest/ComponentSnapshotTests/application/examine/__snapshots__/Decision.spec.js.snap, client/test/jest/ComponentSnapshotTests/application/find/__snapshots__/FindFilter.spec.js.snap, client/test/unit/specs/Conflicts.spec.js, client/test/unit/specs/Decision.spec.js, client/test/unit/specs/ExactMatchConflicts.spec.js, client/test/unit/specs/ExactMatchesRequest.spec.js, client/test/unit/specs/SynonymMatchConflicts.spec.js
- merged sprint branch with changes pushed into prod via master
=> merge master into Sprint 20181122 

client/test/unit/specs/SynonymMatchesRequest.spec.js
*Issue #:bcgov/entity#13*
- jest test update: remove test on @ removal (because it is no longer stripped)
=> jest test update

client/src/components/application/Examine/CompName.vue, client/src/components/application/Examine/RecipeMenu.vue, client/src/store/index.js, client/test/features/specs/support/given.queue.js, client/test/jest/ComponentSnapshotTests/application/examine/__snapshots__/CompName.spec.js.snap, client/test/unit/specs/CompName.spec.js, client/test/unit/specs/Conflicts.spec.js, client/test/unit/specs/ExactMatchConflicts.spec.js, client/test/unit/specs/SynonymMatchConflicts.spec.js, client/test/unit/specs/SynonymMatchesRequest.spec.js
*Issue #:*n/a
Merge sprint branch sprint-20181122 into master post-deployment. Merged via my fork to resolve conflict.
=> Merge sprint-20181122 into Master 

client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue, client/src/store/index.js, client/test/jest/ComponentSnapshotTests/application/examine/Recipe/conflicts/__snapshots__/ConflictList.spec.js.snap, client/test/unit/specs/ExactMatchConflicts.spec.js, client/test/unit/specs/SynonymMatchConflicts.spec.js, client/test/unit/specs/SynonymMatchesData.spec.js, client/test/unit/specs/SynonymMatchesDisplay.spec.js
first version of collapse/expand of synonym results
=> exploring expand/collapse

client/src/components/application/Examine/Recipe/conflicts/ConflictList.vue, client/src/components/application/Examine/RecipeMenu.vue, client/src/store/index.js, client/test/features/specs/support/given.queue.js, client/test/jest/ComponentSnapshotTests/application/examine/Recipe/conflicts/__snapshots__/ConflictList.spec.js.snap, client/test/unit/specs/CobrsPhoneticMatchConflicts.spec.js, client/test/unit/specs/CobrsPhoneticMatchesData.spec.js, client/test/unit/specs/CobrsPhoneticMatchesDisplay.spec.js, client/test/unit/specs/CobrsPhoneticMatchesRequest.spec.js, client/test/unit/specs/PhoneticMatchConflicts.spec.js, client/test/unit/specs/PhoneticMatchesData.spec.js, client/test/unit/specs/PhoneticMatchesDisplay.spec.js, client/test/unit/specs/PhoneticMatchesRequest.spec.js, client/test/unit/specs/SynonymMatchesDisplay.spec.js
*Issue #:bcgov/entity#85*
- character swap + phonetic buckets added
=> phonetic buckets added with jest testing

client/src/components/application/Examine/Decision.vue, client/src/components/application/Find/findFilter.vue, client/src/store/index.js
*Issue #:* bcgov/entity#58
- Set the default date range for the submitted column to 'All' instead of '30 days'
- Fix some of the lists that were potentially empty/null/undefined for tests and causing errors in the tests.
=> Set default submitted date to 'All' instead of '30 Days'

client/src/components/application/Examine/Decision.vue, client/src/store/index.js
*Issue #:* bcgov/entity#58
rollback part
=> roll back breaking change

client/package.json
=> cancel popup bug fix

client/test/unit/specs/CobrsPhoneticMatchConflicts.spec.js, client/test/unit/specs/CobrsPhoneticMatchesData.spec.js, client/test/unit/specs/CobrsPhoneticMatchesDisplay.spec.js, client/test/unit/specs/CobrsPhoneticMatchesRequest.spec.js, client/test/unit/specs/CompName.spec.js, client/test/unit/specs/ConditionRecipe.spec.js, client/test/unit/specs/Conflicts.spec.js, client/test/unit/specs/Decision.spec.js, client/test/unit/specs/ExactMatchConflicts.spec.js, client/test/unit/specs/ExactMatchesRequest.spec.js, client/test/unit/specs/GetConflictsInfo.spec.js, client/test/unit/specs/LandingPage.spec.js, client/test/unit/specs/PhoneticMatchConflicts.spec.js, client/test/unit/specs/PhoneticMatchesData.spec.js, client/test/unit/specs/PhoneticMatchesDisplay.spec.js, client/test/unit/specs/PhoneticMatchesRequest.spec.js, client/test/unit/specs/RequestInfoHeader.alert.spec.js, client/test/unit/specs/RequestInfoHeader.spec.js, client/test/unit/specs/StdHeader.spec.js, client/test/unit/specs/SynonymMatchConflicts.spec.js, client/test/unit/specs/SynonymMatchesData.spec.js, client/test/unit/specs/SynonymMatchesDisplay.spec.js, client/test/unit/specs/SynonymMatchesRequest.spec.js
*Issue #:* n/a
non-functional - reformatted all unit tests for whitespace (tabs vs spaces + brackets)
=> non-functional - reformatted all unit tests for whitespace (tabs vs spaces + brackets)

client/package.json
=> bump version

client/package.json
=> bumped version

client/src/components/application/sections/StdHeader.vue, client/src/store/index.js, client/static/config/configuration.json
=> Admin link fix

client/src/store/index.js, client/test/jest/ComponentSnapshotTests/__snapshots__/App.spec.js.snap, client/test/jest/ComponentSnapshotTests/application/find/__snapshots__/FindFilter.spec.js.snap, client/test/jest/ComponentSnapshotTests/application/stats/__snapshots__/Stats.spec.js.snap, client/test/unit/specs/CobrsPhoneticMatchesRequest.spec.js, client/test/unit/specs/CompName.spec.js, client/test/unit/specs/PhoneticMatchesRequest.spec.js, client/test/unit/specs/SynonymMatchesRequest.spec.js
*Issue #:bcgov/entity#203*
- conflict search no longer errors on empty string search
- NOT dependent on backend
- jest test updates
=> 203 handle empty string search

client/package-lock.json
=> added package-lock.json

client/package.json
=> set bootstrap-vue version

client/Jenkinsfile
=> Update jenkins username

client/Jenkinsfile
=> fixed walter jenkins

client/index.html
=> changed keycloak url to prod sso

client/package.json
=> version update

client/package.json
=> updated vue-template-compiler version per openshift build error message

client/src/components/application/Examine/ActionButtons.vue, client/src/components/application/Examine/CommentsPopUp.vue, client/src/components/application/Find/findFilter.vue, client/src/components/application/NameExamination.vue
name-examination-code-with-us phase-1
Description of changes:
-issue with search results display: ability to automatically parse arrays of data broken.  as a around, changed all instances of the table being fed an array of data with string-templates so the table no longer receives any data as an array.
-usage of bootstrap3 data-* attributes in mixed bootstrap/vuetify layout resulted in data-* attributes being applied to incorrect components. Decision buttons were opening Cancel Modal in error.  added a method for opening and closing the modal using jQuery and removed data-* attributes from mark-up.
=> Fix: search results table -- issue with handling array data input

client/src/components/application/Examine/Decision.vue, client/src/components/application/Examine/RequestInfoHeader.vue, client/src/components/application/Examine/client/ClientInfoHeader.vue
*Issue #:* entity 616, 664-668, 670, 848
- Fixed issue where select menu was attaching to body instead of field
- Changed format of jurisdiction field from 2-letter code to full-text
- Made Applicant Last Name a required field
- Added checks to remove trailing whitespace in name choices
=> Phase 2 fixes

client/package.json
=> Bumped version for namex ui phase 2

client/package.json
=> corrected node version for the pipeline

client/package.json
=> updated version for phase 5

client/package-lock.json, client/package.json, client/test/jest/ComponentSnapshotTests/application/examine/__snapshots__/CompName.spec.js.snap, client/test/jest/ComponentSnapshotTests/application/examine/__snapshots__/RequestInfoHeader.spec.js.snap
- Updated dependencie to eliminate most of the security issues identified by `npm audit`
- Committed package-lock.json
=> Fix for PR #1244

client/src/components/application/Examine/ActionButtons.vue, client/src/components/application/Examine/CompName.vue, client/src/components/application/Examine/Decision.vue, client/src/components/application/Examine/RequestInfoHeader.vue, client/src/store/index.js, client/static/css/main.css, client/static/ui_dropdowns/requesttype.json
- Added BC (benefit company) to list data
- added consentFlag and consent_dt fields.  Fixed issue with expirationDate timezone.
- fixed issue with quick approve button / alt-a shortcut re: decision text
by submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).
=> entity 3299 3290 3660

client/src/components/application/Examine/WordClassificationModal.vue
Have added 'word' key to the JSON object and changed possible value of classification key to either 'DIST' or 'DESC'.
=> Entity 4206 - Modify JSON payload sent from word classfication modal

client/src/components/application/Examine/WordClassificationModal.vue, client/src/store/index.js
fixed issue with Word Classification Modal where additional words were being sent.
=> entity 4333

client/src/App.vue, client/src/components/application/Examine/ActionButtons.vue, client/src/components/application/Examine/RequestInfoHeader.vue, client/src/components/application/NameExamination.vue, client/src/components/application/sections/StdHeader.vue, client/src/store/index.js
- added toggle switch to header area to disable the WordClassificationModal if needed
- changed the functionality of the search box in the header to refresh the data if the currently displayed NR is entered and searched.
=> entity 4431-Add toggle for word classification and fix search box

client/.gitignore, client/package-lock.json
=> 4491 fix versions

client/src/App.vue, client/src/components/application/Examine/WordClassificationModal.vue, client/src/components/application/sections/StdHeader.vue
- Updated word classification modal reversing descriptive and distinctive columns
=> entity 4833

client/index.html
*Issue #:*
- fix for decommissioned url
=> changed auth url

client/src/store/index.js
=> changed restricted words to get (reflecting api change)

client/src/store/index.js
*Issue #:*
changes for api endpoint change
=> updated histories/trademarks for api endpoint change

client/src/store/index.js
=> reverted changes

.gitignore, client/src/components/application/Examine/nwpta/nwpta.vue, client/src/components/application/NameExamination.vue, client/src/store/index.js, client/static/config/configuration.json, functional-tests/src/test/resources/GebConfig.groovy
=> Replace <fragment> tags with <div> tags

client/package-lock.json, client/package.json, client/src/components/application/Find/findFilter.vue, client/src/components/application/sections/StdHeader.vue, client/src/store/index.js, client/static/config/configuration.json, client/static/keycloak/keycloak.json
*Issue #:* bcgov/entity#6609
- column selection
- extra params/fields in search page
- submitted date asc/desc
- usersettings saves column selection
=> column selection, new searches, settings

client/src/components/application/Find/findFilter.vue
=> added in new search column widths and fixed bug

client/src/components/application/Find/findFilter.vue, client/static/css/main.css
=> updated for UX reqs

client/src/components/application/Find/findFilter.vue, client/src/store/index.js, client/static/css/main.css
*Issue #:* bcgov/entities#6609
- added custom submitted date pickers
- fixed sorting issue
=> custom submitted date

client/src/components/application/Find/findFilter.vue
=> extend drop downs fully for search

client/src/components/application/Find/findFilter.vue, client/static/css/main.css
=> final UX updates

client/src/components/application/Transactions.vue
*Issue #:*
- small update to last commit
=> small fixes

client/src/components/application/Transactions.vue, client/src/store/index.js
*Issue #:* https://github.com/bcgov/entity/issues/6423
- ux fixes/updates
=> ux fixes/updates

client/src/components/application/Transactions.vue
=> tiny ux update

client/src/components/application/Transactions.vue
=> txn update for no data / error msg

client/src/components/application/Transactions.vue
=> changed no data msg

client/src/components/application/Transactions.vue
*Issue #:* https://github.com/bcgov/entity/issues/7810
=> added overflow to request type

client/src/components/application/Examine/CompName.vue, client/src/components/application/Transactions.vue
=> 7838 make consent info wrap

client/src/components/application/Examine/Recipe/conflicts/conflictInfoType/NamesMatch.vue, client/src/components/application/Examine/Recipe/history/HistoryInfo.vue, client/src/components/application/Examine/RequestInfoHeader.vue
=> removed submit count

client/src/components/application/Find/findFilter.vue
*Issue #:* https://github.com/bcgov/entity/issues/7708
- search count adjust is no longer needed with new name search implementation
=> removed search count adjust

client/package-lock.json, client/package.json, client/src/components/application/Examine/InfoHeaderPopup.vue, client/src/components/application/Examine/RequestInfoHeader.vue, client/src/store/index.js
*Issue #:* /bcgov/entity#7777
* Added consumedBy to info header.
* Removed Ab/Sk Columns.
* Expanded NOB Column.
=> 7777 info header updates

client/src/components/application/Transactions.vue, client/static/css/main.css, client/static/css/variables.css
*Issue #:* /bcgov/entity#8245
- refactored whitespace, columns, fonts, colours, etc
- deleted obsolete global classes
- WIP
=> Refactor transaction history layout

client/src/components/application/Transactions.vue
*Issue #:* /bcgov/entity#8245
- made header sticky
- dynamically adjust list height
- updated font sizes
- created local helper classes (not in current Vuetify version)
- deleted unused style class
- misc cleanup
=> Affixed header + misc updates

client/src/components/application/Transactions.vue
*Issue #:* /bcgov/entity#8245
- tweaked font sizes
- tweaked whitespace
- added page resize handler
=> Tweaked font sizes and whitespace + added page resize handler

client/src/components/application/Transactions.vue, client/src/store/index.js
*Issue #:* /bcgov/entity#8246
- added decision text to transaction names
- added classnames for unit testing purposes
- fixed a code error (seen in unit tests)
=> Added decision text to transaction names

client/package-lock.json, client/package.json, client/src/axios-auth.js, client/src/components/application/Examine/WordClassificationModal.vue, client/src/components/application/Transactions.vue, client/src/components/application/sections/StdHeader.vue
*Issue #:* bcgov/entity#8437
- fixed error object checks
- misc cleanup
- updated app version
*Steps to reproduce:*
1. login to namex
2. select a DRAFT NR
3. examine the NR
4. click Approve Name
5. select any of the words as Distinctive or Descriptive
6. click Done
7. see error (it was previously crashing some code, at least partly in the background; now the error is "handled")
=> 8437 Fixed a bug (possibly unrelated)

client/src/components/application/Examine/ActionButtons.vue, client/src/components/application/Examine/RequestInfoHeader.vue, client/src/components/application/Find/findFilter.vue, client/src/components/application/Transactions.vue, client/src/store/index.js, client/test/jest/ComponentSnapshotTests/application/examine/Recipe/conflicts/conflictInfoType/__snapshots__/NamesMatch.spec.js.snap, client/test/jest/ComponentSnapshotTests/application/examine/Recipe/history/__snapshots__/HistoryInfo.spec.js.snap, client/test/jest/ComponentSnapshotTests/application/stats/__snapshots__/Stats.spec.js.snap, client/test/unit/specs/transactions.spec.js
=> 8832 use NR State - CONSUMED, EXPIRED

client/package-lock.json, client/package.json
*Issue #:* https://app.zenhub.com/workspaces/entity-5bf2f2164b5806bc2bf60531/issues/bcgov/entity/8760
*Updated Version for release
=> Version bump for release 2.18

client/package-lock.json, client/package.json, client/src/store/index.js, client/test/unit/specs/transactions.spec.js
*Issue #/bcgov/entity#10246
Change the expirdation_date_time to 23:59pm instead of 00:01am
consent_date_time is not being used set to 00:00am
=> 10246 update expiry date time logic

client/package-lock.json, client/package.json, client/src/components/application/Examine/RequestInfoHeader.vue, client/src/components/application/Transactions.vue, client/src/store/index.js
*Issue: /bcgov/entity#8558
Add Home Jurisdiction Number to RequestHeader when NR is being displayed
Add Home Jurisdiction Name and Number when Transaction History of NR is displayed
=> 8558_display_xpro_homejuris_info

client/package-lock.json, client/package.json, client/src/axios-auth.js, client/src/components/application/Examine/RequestInfoHeader.vue
*Issue #:*
https://github.com/bcgov/entity/issues/12518
1. added the condition in axios error processing of corp not found error to avoid the error popup show up (the error shows up under the corpNum input field already)
2. removed @input="$v.previousNr.$touch() from corpNum v-text-field. The validation goes through multiple times if this property set up.
3. allow validate corpNum with/without the prefix 'BC' to reduce the chance a staff change corpNum
=> #12518  Change of Name NR's for Incorporations - frustrating and inefficient process about corpNum validation

client/package-lock.json, client/package.json, client/src/components/application/Examine/RequestInfoHeader.vue, client/static/keycloak/keycloak.json, client/static/keycloak/keycloakdev.json, client/static/keycloak/keycloaktest.json
=> 14184 display examiner

client/package.json, client/src/axios-auth.js, client/src/components/application/Examine/RequestInfoHeader.vue
*Issue #:*
https://github.com/bcgov/entity/issues/14822
validate corp number from both entities and colin
=> 14822 validate corp number from entities

client/index.html
=> Update hardcode url.

client/package-lock.json, client/package.json, client/src/components/application/sections/StdHeader.vue, client/src/store/index.js
*Issue #:*
https://github.com/bcgov/entity/issues/16865
Add Priority Queue switch at top banner to pull next NR from different queue (priority or others) for Examiners.
=> 16865 support Priority Queue switch

.eslintrc.js, __tests__/LandingPage.specs.ts, __tests__/Search.specs.ts, components/AppHeader.vue, components/SearchBox.vue, enums/dropdownEnums.ts, enums/routes.ts, nuxt.config.ts, package-lock.json, package.json, pages/HomePage.vue, pages/SearchPage.vue, pages/index.vue, plugins/fontawesome.ts, store/searchfilters.ts
*Issue #16934*
Setup for the search page in name-examination. 
=> Search page setup

.env.example, .firebaserc, .github/workflows/ci.yml, .gitignore, .npmrc, .nvmrc, .simple-git-hooks.json, README.md, app.vue, components/AppBanner.vue, components/AppHeader.vue, devops/cloudbuild-pr.yaml, devops/vaults.env, firebase.json, middleware/initKeycloak.global.ts, nuxt.config.ts, package-lock.json, package.json, plugins/firebase.client.ts, plugins/fontawesome.ts, pnpm-lock.yaml, store/fetchstatus.ts, store/searchfilters.ts, util/config-helper.ts, util/constants.ts
*Issue #:*
1. upgrade to Node 20.5.1;
2. setup preview site;
3. setup banner using firebase remote config;
4. setup CD flow;
5. Clean up code; ( not done)
=> CD setup and banner.

firebase.json
*Issue #:* #15225
https://app.zenhub.com/workspaces/names-team-space-65133ae62fc06d1008f59331/issues/gh/bcgov/entity/15225
Testing Cache settings
=> testing cache settings 

client/package-lock.json, client/package.json, client/src/components/application/Stats/Stats.vue, client/static/css/main.css
*Issue #:*
https://github.com/bcgov/entity/issues/9296
- Add 'My Stats' checkbox and Total Name Examined to the stats page
=> 9296 nameX - self-serve statistics for examiners

client/package-lock.json, client/package.json, client/static/ui_dropdowns/requesttype.json
*Issue #18962: NAMES /Name request type for BC COMPANY - ULC TO BC CONVERSION /Dec 8 /NAMEX
https://github.com/bcgov/entity/issues/18962
fixed dropdown display according to entity type groups
=> 18962 bc ulc conversion

client/package-lock.json, client/package.json, client/static/ui_dropdowns/requesttype.json
*Issue #18962 -  NAMES /Name request type for BC COMPANY - ULC TO BC CONVERSION /Dec 8 /NAMEX
Updating group for  BC COMPANY - ULC TO BC CONVERSION
=> #18962 - NAMES /Name request type for BC COMPANY - ULC TO BC CONVERSION /Dec 8 /NAMEX

components/EditableTextBox.vue, components/NameRequestTypeInfo.vue, components/app_header/Container.vue, components/examine/decision/Header.vue, components/examine/decision/index.vue, components/examine/names_list/Editable.vue, components/examine/recipe/SearchInputs.vue, components/examine/recipe/history/Info.vue, components/examine/recipe/match/Names.vue, components/examine/recipe/match/index.vue, components/examine/request_info/dates_and_expiry/ExpiryAndConsentEditable.vue, enums/filter-dropdowns.ts, layouts/default.vue, package-lock.json, pages/Examine.vue, store/examine/conflicts.ts, store/examine/index.ts, types/index.ts
*Issue #:*
bcgov/entity#20018
bcgov/entity#20019
bcgov/entity#20005
bcgov/entity#19984
bcgov/entity#20009
bcgov/entity#19983
bcgov/entity#19980
bcgov/entity#19985
bcgov/entity#19978
bcgov/entity#19979
bcgov/entity#19981
Part of the Vue 3 upgrade.
This PR implements bug fixes for the tickets listed above. In addition, some function names in the examine store were renamed, and error handling was added for recipe area loading.
=> Bug fixes part 1

components/app_header/Container.vue, components/examine/request_info/dates_and_expiry/ExpiryAndConsentEditable.vue, enums/codes.ts, package-lock.json, pages/Examine.vue, plugins/firebase.client.ts, plugins/keycloak.client.ts, store/examine/index.ts, store/search.ts, types/index.ts
*Issue #:*
bcgov/entity#20043
bcgov/entity#20044
bcgov/entity#20040
bcgov/entity#20041
bcgov/entity#20045
Part of the Vue 3 upgrade.
This PR implements fixes for the bugs listed above.
=> Bug fixes part 2

components/app_header/Container.vue, devops/vaults.env, enums/routes.ts, nuxt.config.ts
=> Fix admin link

components/Chips.vue, components/GlobalErrorDialog.vue, components/PopupDialog.vue, components/app_header/Container.vue, components/app_header/NavLink.vue, components/examine/decision/select/Conflicts.vue, components/examine/names_list/Editable.vue, components/examine/recipe/SearchInputs.vue, components/examine/recipe/conflicts/ListItem.vue, components/examine/request_info/AdditionalInfo.vue, components/transactions/Header.vue, package-lock.json, pages/Examine.vue, store/examine/conflicts.ts, store/examine/index.ts, store/examine/payments.ts, types/index.ts, util/index.ts
*Issue #:*
bcgov/entity#20204
bcgov/entity#20155
bcgov/entity#20145
bcgov/entity#20073
Part of the Vue 3 upgrade.
This PR implements the fixes for the tickets listed above. Additionally the following refactors were performed:
- renamed `runManualRecipe` to `fetchAndLoadRecipeData`
- changed error dialog style
- replaced `response.status === 200` with `response.ok`
- fix admin link showing as always highlighted in PR builds
- renamed and reorganized reset functions in examine store
=> Bug fixes part 3

components/EditableTextBox.vue, components/NameRequestTypeInfo.vue, components/app_header/Container.vue, components/examine/decision/Header.vue, components/examine/decision/index.vue, components/examine/names_list/Editable.vue, components/examine/recipe/SearchInputs.vue, components/examine/recipe/history/Info.vue, components/examine/recipe/match/Names.vue, components/examine/recipe/match/index.vue, components/examine/request_info/dates_and_expiry/ExpiryAndConsentEditable.vue, data/request_type_rules.json, data/request_types.json, devops/vaults.env, enums/codes.ts, enums/filter-dropdowns.ts, enums/routes.ts, nuxt.config.ts, package-lock.json, package.json, pages/Examine.vue, pages/Stats.vue, plugins/firebase.client.ts, plugins/keycloak.client.ts, store/examine/conflicts.ts, store/examine/index.ts, store/search.ts, store/stats.ts, types/index.ts, util/namex-api.ts
*Issue #:*
https://github.com/bcgov/entity/issues/19736
- update requst_type_rules and request_type
- add Stats page
=> #19736 update request_type_rules and request_type for #18962 and #18504

components/Chips.vue, components/ListSelect.vue, components/examine/QuickActionButtons.vue, components/examine/decision/select/Conflicts.vue, components/examine/header/RequestEditInputs.vue, components/examine/recipe/compare/Item.vue, components/examine/recipe/conflicts/ListItem.vue, data/request_types.json, package-lock.json, pages/Examine.vue, store/examine/index.ts, util/request-type.ts
*Issue #:*
bcgov/entity#20204
bcgov/entity#20155
bcgov/entity#20233
Part of the Vue 3 upgrade.
This PR fixes the previous implementation for bcgov/entity#20204 and bcgov/entity#20155. It also fixes bcgov/entity#20233.
=> Bug fixes part 4

components/SearchInput.vue, components/examine/decision/RequestorMessage.vue, package.json
*Issue #:*
bcgov/entity#20287
Fixes the clear button size when the requestor message is edited, and the reset button on the recipe search inputs.
=> Fix requestor message clear button

components/Accordion.vue, components/examine/recipe/conflicts/Bucket.vue, components/examine/recipe/conflicts/List.vue, components/examine/recipe/conflicts/ListItem.vue, package.json, store/examine/recipe.ts, util/emitter.ts
*Issue #:*
bcgov/entity#20335
bcgov/entity#20336
This PR fixes some bugs introduced by PR #1440.
- Fixed exact match conflicts not being able to be focused
- Fixed clicking checkbox to select conflicts
=> 20335/20336 Fix keyboard navigation

composables/mnemonic.ts, package-lock.json, package.json
*Issue #:*
bcgov/entity#20343
This PR prevents the default browser actions from firing when a mnemonic shortcut is pressed.
=> 20343 Fix alt + E shortcut opening browser settings

package-lock.json, package.json, store/examine/index.ts
*Issue #:*
https://github.com/bcgov/entity/issues/20593
small fix to allow currentNameObj.value.state is undefined
=> #20593 error occurs when 'Approve' a name

components/Accordion.vue, components/examine/recipe/conflicts/Bucket.vue, package-lock.json, package.json
*Issue #:*
bcgov/entity#20592
This PR fixes a bug where the recipe area sometimes scrolls too far when a conflict list is expanded.
=> 20592 Fix recipe area scrolling too far when expanding list

components/app_footer/NavLink.vue, components/app_footer/VersionInfo.vue, components/app_footer/index.vue, layouts/default.vue
*Issue #:*
Added app footer
- index is the base for the footer
- navlink is a link for the footer
- version number is the tooltip that displays the proper version numbers in the footer
=> Aded App_Footer with tooltip to grab version numbers

components/app_footer/NavLink.vue, components/app_footer/VersionInfo.vue, components/app_footer/index.vue, layouts/default.vue
=> Added footer with tooltip to display version numbers

.github/workflows/e2e.yml, devops/cloudbuild-pr.yaml, devops/vaults.env
Restored the Devops directory as I accidently removed it.
=> fix: accidently left out the devops dir

.github/workflows/cd.yml
*Issue: With the latest path changes to the repo the cd.yml needed to be updated.
cd.yaml to a new call as per @pwei1018 
=> update: update the cd.yaml for the new location

app/components/search/ResultsBox.vue, app/package-lock.json, app/package.json
*Issue #:*
Bug Fix: Made it so text input filters worked again
- This will also make the Cypress Smoke test work
=> 20339 - Make search filters work so cypress works

testing/cypress/e2e/smoke/smoke-10-brokenlinks.cy.ts, testing/cypress/pageObjects/homePage.ts
*Issue #:* This is not going to be merged into main, this is on a cypress-playground branch which will not be merged yet. 
=> Test pr not to be merged

testing/cypress/e2e/smoke/smoke-10-brokenlinks.cy.ts, testing/cypress/e2e/smoke/smoke-20-e2e.cy.ts, testing/cypress/pageObjects/homePage.ts, testing/cypress/support/commands.ts, testing/cypress/support/global.d.ts
=> Another cypress

testing/cypress/e2e/smoke/smoke-10-brokenlinks.cy.ts, testing/cypress/e2e/smoke/smoke-20-e2e.cy.ts, testing/cypress/e2e/smoke/smoke-40-rejections.cy.ts, testing/cypress/pageObjects/homePage.ts
=> 22417 update smoke tests

app/middleware/keycloak.global.ts, app/package-lock.json, app/package.json, app/pages/error.vue
*Issue #:*
https://github.com/bcgov/entity/issues/24487
Only staff members are authorized to access this application
=> #24487 Access to the application is restricted to staff members only

app/middleware/keycloak.global.ts, app/package-lock.json, app/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/26221
Allow names_viewer to login name-examination
=> #26221 allow names_viewer to login name-examination

.github/workflows/ci.yml
*Issue #:*
fix the error: 
update ubuntu version from 20.04 to 24.04.1
=> Update ci.yml ubuntu version

app/components/transactions/EntryList.vue, app/components/transactions/NotificationEntry.vue, app/package.json, app/types/index.ts, app/util/namex-api.ts
*Issue #:*
https://github.com/bcgov/entity/issues/28408
Display and resend notifications
=> #28408 resend notification

app/assets/css/main.scss, app/components/ComboSelect.vue, app/components/search/ResultsBox.vue, app/pages/Stats.vue, app/store/examine/conflicts.ts
*Issue #:*
https://github.com/bcgov/entity/issues/29880
update possible conflict to match the changes in namex
=> 29880 - update possible conflict to match the changes in namex
